apiVersion: v1
kind: Pod
metadata:
   labels:
     test: liveness
   name: mypod
spec:
  containers:
  - name: mycont
    image: ubuntu
    args:
    - /bin/bash
    - -c
    - touch /tmp/myfile; sleep 10000
    livenessProbe: 
      exec:
        command: # command to run periodically
        - cat
        - /tmp/myfile
      initialDelaySeconds: 5 
      periodSeconds: 5 
      timeoutSeconds: 30  
