apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sai; sleep 5; done"]
    volumeMounts:
     - name: testsecret # Volume mount name
       mountPath: "/tmp/mysecrets" 
  volumes:
  - name: testsecret # Volume mount name
    secret:
      secretName: mysecret 
